RedCollege/redcollege-nuxt-module

- src/runtime/repository/modules/planificaciones/planificacion.ts
- src/runtime/repository/modules/planificaciones/unidad.ts
Se corrigen las importaciones relacionadas con los models de unidad y planificacion
- [ x] Corrección de errores
Se corrige las importaciones de los models de unidade y planificacion
1. Pruebas durante el desarrollo
Asegúrate de que todas estas tareas se han completado antes de solicitar la revisión:
- [x ] He realizado una revisión personal de mi propio código.
- [x ] He seguido las convenciones de estilo del código de este proyecto.
- [x ] He documentado mi código, especialmente en áreas difíciles de entender.
> Fix import path for planificaion and unidad modules

- src/runtime/models/Planificacion/planificacion.ts
- src/runtime/repository/modules/planificaciones/planificacion.ts
Se corrige el tipo de respuesta que da la funcion getAll para la obtención de las planificaciones
- [ x] Corrección de errores
Se corrige el tipo de dato que retorna la funcion getAll encargado de retornar las planificaciones
1. Pruebas durante el desarrollo
Asegúrate de que todas estas tareas se han completado antes de solicitar la revisión:
- [x ] He realizado una revisión personal de mi propio código.
- [x ] He seguido las convenciones de estilo del código de este proyecto.
- [x ] He documentado mi código, especialmente en áreas difíciles de entender.
> Fix interfaz de retorno de getAll en planificacion

- src/runtime/models/Planificacion/planificacion.ts
Se corrige el tipo de respuesta que da la funcion getAll para la obtención de las planificaciones
- [ x] Corrección de errores
Se corrige el tipo de dato que retorna la funcion getAll encargado de retornar las planificaciones
1. Pruebas durante el desarrollo
Asegúrate de que todas estas tareas se han completado antes de solicitar la revisión:
- [x ] He realizado una revisión personal de mi propio código.
- [x ] He seguido las convenciones de estilo del código de este proyecto.
- [x ] He documentado mi código, especialmente en áreas difíciles de entender.
> Update planificacion.ts interface

- src/runtime/repository/modules/planificaciones/planificacion.ts
En esta PR se añade al modulo la función que se encarga de enviar a la api el id de una de las planificaciones y esta es duplicada
( en este repo no está  autogenerando la planitilla de las pr )
> Seccion planificacion

- src/runtime/repository/modules/planificaciones/planificacion.ts
En esta pr se agregan los parametros para poder filtrar las planificaciones en la funcion de getAll() referente a las planificaciones.
> Params en getall de las planificaciones

- src/runtime/repository/modules/planificaciones/planificacion.ts
> Correcciones en las rutas de la seccion de planificacion

- playground/pages/index.vue
- src/runtime/components/ui/toggle-group/ToggleGroup.vue
- src/runtime/components/ui/toggle-group/ToggleGroupItem.vue
- src/runtime/components/ui/toggle-group/index.ts
- src/runtime/components/ui/toggle/Toggle.vue
- src/runtime/components/ui/toggle/index.ts
se agrega el componente toggle  y toogle-group
> agregado toggle y toggle-group

- playground/pages/index.vue
- src/runtime/models/Establecimiento/asignatura_curricular.ts
- src/runtime/models/Establecimiento/asignatura_sige.ts
- src/runtime/models/Establecimiento/curso_asignatura.ts
- src/runtime/plugins/api.ts
- src/runtime/repository/modules/establecimiento/establecimiento.ts
- src/runtime/utils/apiModuleFactory.ts
En el presente pull request se han actualizado los modelos correspondientes al establecimiento, así como la ruta para obtener las asignaturas de un curso en específico
> 2 crear models y rutas para establecimiento

- src/runtime/repository/modules/establecimiento/establecimiento.ts
En el presente pr se ha agregado el metodo para obtener los cursos de un establecimiento por año, atendiendo a las necesidades del issue [https://github.com/RedCollege/backend-next/issues/8](https://github.com/RedCollege/backend-next/issues/8)
> Agregado metodo para obtener los cursos de un establecimiento por año

- package-lock.json
- src/runtime/models/Planificacion/itemEntradaCurricular.ts
- src/runtime/models/Planificacion/planificacion.ts
- src/runtime/models/Planificacion/unidad.ts
- src/runtime/repository/modules/planificaciones/planificacion.ts
En el presente PR se introducen los cambios con una nueva ruta para clonar planificacion, se agrego al planificacionModule y se actualizaron los models
> Added route to clone planificacion

- src/runtime/models/Auth/usuario.ts
- src/runtime/models/Establecimiento/curso.ts
- src/runtime/models/Establecimiento/rol.ts
- src/runtime/repository/modules/establecimiento/establecimiento.ts
en el presente pr se agrega el parametro isDinamico para filtrar por ese valor en el metodo getAllCursosByEstablecimiento
> Agregar parametro isDinamico para filtrar por ese valor

- src/runtime/repository/modules/establecimiento/curso.ts
El presente PR introduce cambios para arreglar el endpoint para consumir las asignaturas por sige Id
> FIX(repository): Arreglar ruta para consumir asignaturas por sige id

- src/runtime/repository/modules/planificaciones/planificacion.ts
- src/runtime/repository/modules/planificaciones/unidad.ts
El presente PR modifica las rutas referentes a unidades a su respectivo repository y agrega cambios de params a esas rutas
> FIX(repository): Arreglar rutas de unidades

- src/runtime/models/General/archivo.ts
- src/runtime/models/General/index.ts
- src/runtime/models/Planificacion/unidad.ts
- src/runtime/models/index.ts
- src/runtime/plugins/api.ts
- src/runtime/repository/modules/general/auxiliar.ts
- src/runtime/repository/modules/planificaciones/unidad.ts
- src/runtime/utils/apiModuleFactory.ts
En el presente pr se ha creado el repository para auxiliar dentro de la carpeta general. Se ha actualizado el repository de unidades
> 8 crear models y y rutas para archivos

- src/runtime/models/General/archivo.ts
- src/runtime/repository/modules/general/auxiliar.ts
en el presente pr se ha arreglado el tipo para un promise y agregado un segmento de ruta faltante en auxiliar
> 9 fix tipos en auxiliar

- src/runtime/models/Planificacion/planificacion.ts
##Detalles de la PR
se corrige la interfeaz de IPlanificaciones, se elimina el atributo libro ya que se accede a este a travez de la relación con curso
> Added libro interface

- src/runtime/repository/modules/planificaciones/unidad.ts
El presente PR introduce una nueva ruta para relacionar items a una unidad mediante el uso de un arreglo de ids
> FEAT(unidad): Agregar items a la unidad

- src/runtime/models/Planificacion/index.ts
En el presente PR se introduce el export en el index.ts de Icontenido
> FIX(models): Agregar models IContenido

- src/runtime/models/Planificacion/contenido.ts
En el presente pr se ha agregado el campo is_cumplido a la interfaz de contenido
> feat: Agregar campo is_cumplido a la interfaz de Contenido

- src/runtime/models/Planificacion/adecuacion_curricular.ts
En el presente pr se ha cambiado la interface de IAdecuacionCurricularForm, para que coincida con la estructura de la data a enviar
> 17 cambiar interfaz para crear adecuaciones curriculares

- src/runtime/repository/modules/planificaciones/adecuacion_curricular.ts
En el presente pr se han agregado los params de nombre y asignatura para filtrar
> feat: Agregar params de nombre y asignatura para filtrar

- src/runtime/models/Curriculum/item_entrada_curricular.ts
- src/runtime/models/Planificacion/adecuacion_curricular.ts
En el presente pr se ha agregado la relacion de contenido a la interfaz de IAdecuacionCurricular, además de agregar adecuacionCurricular en la iterfaz de IItemEntradaCurricular como opcional
> Agregar relacion de contenido a IAdecuacionCurricular

- src/runtime/models/Comunicacion/mensaje.ts
- src/runtime/repository/modules/comunicacion/adjunto.ts
En el presente pr se ha agregado el campo de adjuntosIds para la interface de mensaje, además de crear los métodos para subir y eliminar adjuntos en comunicaciones
> 18 agregar campo adjuntos ids en modelo de mensaje

- src/runtime/repository/modules/comunicacion/adjunto.ts
En el presente pr se ha hecho una corrección del metodo de eliminar el adjunto
> fix: Corregir metodo para eliminar adjunto por url

- package-lock.json
- src/runtime/models/Planificacion/marcador.ts
- src/runtime/models/Planificacion/unidad.ts
- src/runtime/repository/modules/planificaciones/marcador.ts
- src/runtime/utils/apiModuleFactory.ts
implementar marcadores de la unidad
> FEAT(marcadores):Implementar marcadores

- src/runtime/models/Planificacion/unidad.ts
Aregado nueva propiedad a IUnidad, llamada cantidadContenidosAsociados de tipo number.
> feat(planificacion): modificar interfaz de la unidad

- src/runtime/repository/modules/planificaciones/contenido.ts
El presente PR contiene los cambios necesarios para agregar la ruta que duplica un contenido y toda su informacion
> FEAT(contenidoModule): Agregar ruta para duplicar un contenido

- src/runtime/models/Planificacion/contenido.ts
El siguiente PR actualiza el modelo de contenidos con relaciones nuevas agregadas como la de adecuaciones curriculares y el campo isVisible para deshabilitar el contenido
> UPDATE(models-contenido): Actualizar el model de IContenido

- src/runtime/models/Planificacion/planificacion.ts
- src/runtime/repository/modules/planificaciones/planificacion.ts
- src/runtime/repository/modules/planificaciones/unidad.ts
El parametro se llama isUnidad y le envia al back el id de la unidad en caso de venir, de lo contrario null
> feat(getPlanificacionById) agregando nuevo parametro para cargar solo una unidad de la planificacion

- src/runtime/repository/modules/general/auxiliar.ts
En el presente pr se ha agregado la posibilidad de que se envie un parametro opcional para permitir la previsualizacion de archivos
> Parametro opcional para permitir elegir entre previsualizar y descargar archivos

- src/runtime/components/ui/progress/Progress.vue
En el presente pr se ha agregado una prop para el componente progress para que se muestre el porcentaje de la barra de progreso de manera condicional
> feat: Agregar prop para el componente progress

- package-lock.json
- package.json
- playground/pages/animations.vue
- playground/tsconfig.json
- tsconfig.json
En este PR se agrega la dependencia del plugin necesario para poder tener soporte de TS en el template utilizando PUG
> FEAT: Agregar soporte de TS en el template de pug

- playground/pages/[establecimientoid]/[periodo].vue
- src/runtime/components/ui/progress/Progress.vue
- src/runtime/components/ui/progress/index.ts
> feat(descargable_curso) cambiando como se muestra el value

- src/runtime/components/ui/tabs/index.ts
> feat(tabs_component): Creando nueva variante para el tab trigger

- src/runtime/models/Planificacion/contenido.ts
- src/runtime/repository/modules/planificaciones/contenido.ts
En el presente pr se ha extendido el método de duplicarContenido
> FEAT: Extender metodo de duplicarContenido
